[world]
kind = "Contract"
class_hash = "0x799bc4e9da10bfb3dd88e6f223c9cfbf7745435cd14f5d69675ea448e578cd"
address = "0x446f1f19ba951b59935df72974f8ba6060e5fbb411ca21d3e3e3812e3eb8df8"
transaction_hash = "0x7f1456c94b5cc20a043c7acb7e183a31b57b6de82699b062498189f8aae9d0b"
block_number = 3
seed = "dojo_starter"
name = "dojo::world::world"

[base]
kind = "Class"
class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x7ec42d76c6d876b8f219c20b6a152fe35fe2afc62c471b29ba689c2f6a075b3"
class_hash = "0x72c65c5ca0f00edf30c6774e3ceada203f3e1e1840142850a805608aa766e3"
abi = "abis/deployments/KATANA/contracts/actions.json"
reads = []
writes = []
computed = []
name = "dojo_starter::systems::actions::actions"

[[models]]
kind = "DojoModel"
class_hash = "0x23c28dcfad6be01ca6509fdb35fd2bed6622238397613c60da5d387a43c38d0"
name = "dojo_starter::models::moves::moves"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "remaining"
type = "u8"
key = false

[[models.members]]
name = "last_direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2e9c42b868b520d54bff1b7f4c9b91f39bb2e2ad1c39d6484fb5d8a95382e01"
name = "dojo_starter::models::position::position"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "vec"
type = "Vec2"
key = false
